spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: orderflow
    password: orderflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service

server:
  port: 8085

orderflow:
  jwt:
    public-key-location: file:${JWT_PUBLIC_KEY_PATH:docker/secrets/jwt/public_key.pem}
  kafka:
    partitions: 3
    replication-factor: 1
  outbox:
    poll-interval-ms: 500
  payment:
    decline-threshold: 10000.00

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.orderflow: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db
  kafka:
    bootstrap-servers: kafka:19092

orderflow:
  jwt:
    public-key-location: file:${JWT_PUBLIC_KEY_PATH:/run/secrets/jwt/public_key.pem}
